version: 0.1.0

models:
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i4sc-s0.pth
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i4sc-s1000.pth
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i4sc-s2500.pth
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i4sc-s5000.pth

  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i2sc-s0.pth
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i2sc-s1000.pth
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i2sc-s2500.pth
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/stop_iteration/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/stop_iteration/RegNetX-200MF-i2sc-s5000.pth