version: 0.1.0

models:
  - model_name: ResNet18
    dataset: cifar10
    mode: evaluate
    save_name: ResNet18-i4sc
    result_path: result_csv/cifar10/ResNet18/joint_training/evaluate.csv
    weight_path: checkpoints/cifar10/ResNet18/joint_training/ResNet18-i4sc-joint_false_s2500.pth

  - model_name: ResNet18
    dataset: cifar10
    mode: evaluate
    save_name: ResNet18-i2sc
    result_path: result_csv/cifar10/ResNet18/joint_training/evaluate.csv
    weight_path: checkpoints/cifar10/ResNet18/joint_training/ResNet18-i2sc-joint_false_s2500.pth