version: 0.1.0

models:
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i4sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i4sc-sigmoid_sigmoid_s2500.pth

  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i4sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i4sc-tanh_sigmoid_s2500.pth
  
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i4sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i4sc-tanh_tanh_s2500.pth
  
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i4sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i4sc-zero_sigmoid_s2500.pth
  
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i4sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i4sc-random_sigmoid_s2500.pth


  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i2sc-sigmoid_sigmoid_s2500.pth

  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i2sc-tanh_sigmoid_s2500.pth
  
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i2sc-tanh_tanh_s2500.pth
  
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i2sc-zero_sigmoid_s2500.pth
  
  - model_name: RegNetX-3.2GF
    dataset: imagenet
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/imagenet/RegNetX-3.2GF/initialization/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/initialization/RegNetX-3.2GF-i2sc-random_sigmoid_s2500.pth