version: 0.1.0

models:
  - model_name: RegNetX-3.2GF
    mode: evaluate
    save_name: RegNetX-3.2GF-i4sc
    result_path: result_csv/RegNetX-3.2GF/joint_training/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/joint_training/RegNetX-3.2GF-i4sc-joint_false_s2500.pth

  - model_name: RegNetX-3.2GF
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/RegNetX-3.2GF/joint_training/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/joint_training/RegNetX-3.2GF-i2sc-joint_false_s2500.pth