version: 0.1.0

models:
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i4sc-sigmoid_sigmoid_s2500.pth

  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i4sc-tanh_sigmoid_s2500.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i4sc-tanh_tanh_s2500.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i4sc-zero_sigmoid_s2500.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i4sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i4sc-random_sigmoid_s2500.pth


  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i2sc-sigmoid_sigmoid_s2500.pth

  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i2sc-tanh_sigmoid_s2500.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i2sc-tanh_tanh_s2500.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i2sc-zero_sigmoid_s2500.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/RegNetX-200MF/initialization/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/initialization/RegNetX-200MF-i2sc-random_sigmoid_s2500.pth