version: 0.1.0

models:
  - model_name: ResNet18
    dataset: cifar10
    mode: evaluate
    save_name: ResNet18-i2sc
    result_path: result_csv/cifar10/W2A2/evaluate.csv
    weight_path: checkpoints/cifar10/ResNet18/ResNet18-i2sc.pth
  
  - model_name: ResNet50
    dataset: cifar10
    mode: evaluate
    save_name: ResNet50-i2sc
    result_path: result_csv/cifar10/W2A2/evaluate.csv
    weight_path: checkpoints/cifar10//ResNet50/ResNet50-i2sc.pth

  - model_name: MobileNetV2
    dataset: cifar10
    mode: evaluate
    save_name: MobileNetV2-i2sc
    result_path: result_csv/cifar10/W2A2/evaluate.csv
    weight_path: checkpoints/cifar10/MobileNetV2/MobileNetV2-i2sc.pth
  
  - model_name: RegNetX-200MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-200MF-i2sc
    result_path: result_csv/cifar10/W2A2/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-200MF/RegNetX-200MF-i2sc.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: evaluate
    save_name: RegNetX-400MF-i2sc
    result_path: result_csv/cifar10/W2A2/evaluate.csv
    weight_path: checkpoints/cifar10/RegNetX-400MF/RegNetX-400MF-i2sc.pth
    