version: 0.1.0

models:
  - model_name: ResNet18
    mode: evaluate
    save_name: ResNet18-i2sc
    result_path: result_csv/W2A2/evaluate.csv
    weight_path: checkpoints/imagenet/ResNet18/ResNet18-i2sc.pth
  
  - model_name: ResNet50
    mode: evaluate
    save_name: ResNet50-i2sc
    result_path: result_csv/W2A2/evaluate.csv
    weight_path: checkpoints/imagenet/ResNet50/ResNet50-i2sc.pth

  - model_name: MobileNetV2
    mode: evaluate
    save_name: MobileNetV2-i2sc
    result_path: result_csv/W2A2/evaluate.csv
    weight_path: checkpoints/imagenet/MobileNetV2/MobileNetV2-i2sc.pth
  
  - model_name: RegNetX-600MF
    mode: evaluate
    save_name: RegNetX-600MF-i2sc
    result_path: result_csv/W2A2/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-600MF/RegNetX-600MF-i2sc.pth
  
  - model_name: RegNetX-3.2GF
    mode: evaluate
    save_name: RegNetX-3.2GF-i2sc
    result_path: result_csv/W2A2/evaluate.csv
    weight_path: checkpoints/imagenet/RegNetX-3.2GF/RegNetX-3.2GF-i2sc.pth
    