version: 0.1.0

models:
  - model_name: ResNet18
    mode: reconstruction
    save_name: ResNet18-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/W2A2/reconstruct.csv
    save_path: checkpoints/imagenet/ResNet18/ResNet18-i2sc.pth
  
  - model_name: ResNet50
    mode: reconstruction
    save_name: ResNet50-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/W2A2/reconstruct.csv
    save_path: checkpoints/imagenet/ResNet50/ResNet50-i2sc.pth

  - model_name: MobileNetV2
    mode: reconstruction
    save_name: MobileNetV2-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/W2A2/reconstruct.csv
    save_path: checkpoints/imagenet/MobileNetV2/MobileNetV2-i2sc.pth
  
  - model_name: RegNetX-600MF
    mode: reconstruction
    save_name: RegNetX-600MF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/W2A2/reconstruct.csv
    save_path: checkpoints/imagenet/RegNetX-600MF/RegNetX-600MF-i2sc.pth
  
  - model_name: RegNetX-3.2GF
    mode: reconstruction
    save_name: RegNetX-3.2GF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/W2A2/reconstruct.csv
    save_path: checkpoints/imagenet/RegNetX-3.2GF/RegNetX-3.2GF-i2sc.pth
    