version: 0.1.0

models:
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i4sc
    wq_params: {'n_bits': 4, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 4, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'sigmoid'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i4sc-sigmoid_sigmoid_s2500.pth

  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i4sc
    wq_params: {'n_bits': 4, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 4, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i4sc-tanh_sigmoid_s2500.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i4sc
    wq_params: {'n_bits': 4, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 4, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'tanh'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i4sc-tanh_tanh_s2500.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i4sc
    wq_params: {'n_bits': 4, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 4, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'zero'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i4sc-zero_sigmoid_s2500.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i4sc
    wq_params: {'n_bits': 4, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 4, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'random'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i4sc-random_sigmoid_s2500.pth


  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'sigmoid'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i2sc-sigmoid_sigmoid_s2500.pth

  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i2sc-tanh_sigmoid_s2500.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'tanh'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i2sc-tanh_tanh_s2500.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'zero'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i2sc-zero_sigmoid_s2500.pth
  
  - model_name: RegNetX-400MF
    dataset: cifar10
    mode: reconstruction
    save_name: RegNetX-400MF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'random'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: True
    result_path: result_csv/cifar10/RegNetX-400MF/initialization/reconstruct.csv
    save_path: checkpoints/cifar10/RegNetX-400MF/initialization/RegNetX-400MF-i2sc-random_sigmoid_s2500.pth