version: 0.1.0

models:
  - model_name: ResNet50
    mode: evaluate
    save_name: ResNet50-i4sc
    result_path: result_csv/ResNet50/joint_training/evaluate.csv
    weight_path: checkpoints/ResNet50/joint_training/ResNet50-i4sc-joint_false_s2500.pth

  - model_name: ResNet50
    mode: evaluate
    save_name: ResNet50-i2sc
    result_path: result_csv/ResNet50/joint_training/evaluate.csv
    weight_path: checkpoints/ResNet50/joint_training/ResNet50-i2sc-joint_false_s2500.pth