version: 0.1.0

models:
  - model_name: RegNetX-3.2GF
    save_name: RegNetX-3.2GF-i4sc
    wq_params: {'n_bits': 4, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 4, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: False

  - model_name: RegNetX-3.2GF
    save_name: RegNetX-3.2GF-i2sc
    wq_params: {'n_bits': 2, symmetric: False, 'channel_wise': True, 'scale_method': 'mse'}
    aq_params: {'n_bits': 2, symmetric: False, 'channel_wise': False, 'scale_method': 'mse',
                    'leaf_param': True, 'prob': 0.5}
    constraint_fn: 'sigmoid'   #constraint function for the rounding value
    initialization_fn: 'tanh'  #initialization function for the rounding value
    scale_iter: [2500]
    joint_training: False